   services:
     crawler:
       build:
         context: .
         dockerfile: crawler/Dockerfile
       environment:
         - DATABASE_URL=postgres://rainsfall:262912@postgres:5432/search_engine
       depends_on:
         - postgres
       working_dir: /app
       command: ["/app/crawler"]

     postgres:
       image: postgres:13
       environment:
         - POSTGRES_USER=rainsfall
         - POSTGRES_PASSWORD=262912
         - POSTGRES_DB=search_engine
       ports:
         - "5434:5432"
       volumes:
         - postgres_data:/var/lib/postgresql/data
         - ./storage/src/scripts:/docker-entrypoint-initdb.d/

   volumes:
     postgres_data:

