global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'crawler'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['crawler:9092'] 
  - job_name: 'ranker'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ranker:9093']  

  - job_name: 'indexer'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['indexer:9091'] 