global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'crawler'
    static_configs:
      - targets: ['crawler:9091']
    metrics_path: '/metrics'

  - job_name: 'indexer'
    static_configs:
      - targets: ['indexer:9092']
    metrics_path: '/metrics'

  - job_name: 'ranker'
    static_configs:
      - targets: ['ranker:9093']
    metrics_path: '/metrics'