[package]
name = "monitoring"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
prometheus = "0.13.4"
lazy_static = "1.5.0"
serde = { version = "1.0.209", features = ["derive"] }
log = "0.4.22"
env_logger = { version = "0.11.5", features = ["color"] }
