[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
tantivy = "0.22.0"
serde = { version = "1.0.209", features = ["derive"] }
tokio = { version = "1.39.3", features = ["full"] }
thiserror = "1.0"
config = "0.14.0"
tracing = "0.1"
toml = "0.8.19"
structopt = "0.3.26"
futures = "0.3.30"
rayon = "1.10.0"