name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info

jobs:
  build-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        mkdir -p $DOCKER_CONFIG/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
        chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
        docker compose version

    - name: Build Docker images
      run: docker compose -f deploy/docker/docker-compose.yml build

  verify-core-services:
    name: Verify Core Services
    needs: build-images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Start core services
      run: |
        docker compose -f deploy/docker/docker-compose.yml up -d
        echo "Waiting for services to initialize..."
        sleep 30

    - name: Check web frontend
      run: |
        curl -f http://localhost:3000 || exit 1
        echo "✓ Web frontend is up"

    - name: Check crawler API
      run: |
        curl -f http://localhost:8000/health || exit 1
        echo "✓ Crawler service is up"

    - name: Check Elasticsearch
      run: |
        curl -f http://localhost:9200/_cluster/health || exit 1
        echo "✓ Elasticsearch is up"

    - name: Cleanup core services
      if: always()
      run: docker compose -f deploy/docker/docker-compose.yml down -v

  verify-metrics:
    name: Verify Metrics Endpoints
    needs: build-images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Start services
      run: |
        docker compose -f deploy/docker/docker-compose.yml up -d
        echo "Waiting for metrics to initialize..."
        sleep 30

    - name: Check metrics endpoints
      run: |
        curl -f http://localhost:9091/metrics || exit 1
        echo "✓ Crawler metrics endpoint is up"
        curl -f http://localhost:9092/metrics || exit 1
        echo "✓ Indexer metrics endpoint is up"
        curl -f http://localhost:9093/metrics || exit 1
        echo "✓ Ranker metrics endpoint is up"

    - name: Show logs on failure
      if: failure()
      run: |
        echo "Metrics verification failed. Showing logs:"
        docker compose -f deploy/docker/docker-compose.yml logs

    - name: Cleanup metrics services
      if: always()
      run: docker compose -f deploy/docker/docker-compose.yml down -v

  deploy:
    name: Deploy (Mock)
    needs: [verify-core-services, verify-metrics]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy notification
      run: |
        echo "🚀 Build and verification successful!"
        echo "Services ready for deployment:"
        echo "✓ Web Frontend (Port 3000)"
        echo "✓ Crawler Service (Port 8000)"
        echo "✓ Indexer Service"
        echo "✓ Ranker Service"
        echo "✓ Monitoring Stack (Prometheus:9090, Grafana:3001)" 
