name: Crawler CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'crawler/**'
      - 'storage/**'
      - '.github/workflows/components/crawler-ci-cd.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'crawler/**'
      - 'storage/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Execute Unit Tests
        run: |
          cd crawler
          cargo test --verbose

  build-and-deploy:
    name: Build and Deploy Docker Image
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./crawler/Dockerfile
          push: true
          tags: rainsfal1/search-engine-crawler:${{ github.ref == 'refs/heads/main' && 'latest' || 'develop' }}
